swagger: '2.0'
info:
  title: WAZIUP API
  description: Applications API
  version: 1.0.0
host: '127.0.0.1:8000'
schemes:
  - http
basePath: /api/v1
produces:
  - application/json
consumes:
  - application/json
parameters:
  domainParam:
    name: "domain"
    in: "path"
    required: false 
    type: "string"
    example: "cdupont"
  sensorId:
    name: "sensor_id"
    in: "path"
    required: true 
    type: "string"
    example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
  measurementId:
    name: "measurement_id"
    in: "path"
    required: true 
    type: "string"
    example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
definitions:
  Sensor:
    type: object
    required: ["id"]
    properties:
      id:
        type: string
        description: UUID of the sensor
        example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
      gateway_id:
        type: string
        description: UUID of the gateway
        example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
      name:
        type: string
        description: name of the sensor
        example: "Sensor1"
      owner:
        type: string
        description: name of the sensor
        example: "cdupont"
      sensor_kind:
        type: string
        description: kind of the sensor
        example: "Soil temperature sensor"
      measurements:
        type: array
        items:
          $ref: '#/definitions/Measurement'
      location:
        $ref: '#/definitions/Location'
  Location:
    type: object
    description: location is a pair [latitude, longitude] with the coordinates on earth in decimal notation (e.g. [40.418889, 35.89389]).
    properties:
      latitude:
        type: number
        example: 5.3600
      longitude:
        type: number
        example: 4.0083
  Measurement:
    type: object
    properties:
      id:
        type: string
        description: UUID of the measurement 
        example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
      name:
        type: string
        description: name of the measurement
        example: "TC1"
      dimension:
        type: string
        description: physical dimension of the measurement
        example: "temperature"
      unit:
        type: string
        description: unit of the measurement
        example: "Degree C"
      values:
        type: array
        items:
          $ref: '#/definitions/MeasurementValue'
  MeasurementValue:
    type: object
    properties:
      value:
        type: "number"
        format: "float"
        description: value of the measurement 
        example: "25.6"
      timestamp:
        type: "string"
        format: "dateTime"
        description: time of the measurement
        example: "2016-06-08T18:20:27.873Z"
  HistoricalValue:
    type: object
    properties:
      id:
        type: string
        description: UUID of the sensor
        example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
      attribute_id:
        type: string
        description: UUID of the measurement
        example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
      datapoint:
        $ref: '#/definitions/MeasurementValue'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  AuthBody:
    type: object
    title: credentials
    required:
      - username
      - password
    properties:
      username:
        type: string
        description: Admin username
      password:
        type: string
        description: Admin password
  UserUpdateBody:
    type: object
    title: userupdate
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
        description: User's First Name
      lastName:
        type: string
        description: User's Last Name
      id:
        type: string
        description: User id
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header



paths:
  /domains/{domain}/sensors:
    get:
      summary: Sensor data
      description:    
      tags:
        - Sensors
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      responses:
        '200':
          description: 
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Sensor"
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create sensors
      description: Endpoint to create sensing devices.
      tags:
        - Sensors
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Sensor"
      - $ref: '#/parameters/domainParam'
      responses:
        '201':
          description: Sensor created succesfully
        '422':
          description: Unprocessable entity 
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /domains/{domain}/sensors/{sensor_id}:
    get:
      summary: get sensor
      description:    
      tags:
        - Sensors
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      responses:
        '200':
          description: 
          schema:
            $ref: "#/definitions/Sensor"
        '400':
          description: Bad request
        '404':
          description: Not Found
        '422':
          description: Unprocessable entity 
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Delete sensor
      description:    
      tags:
        - Sensors
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      responses:
        '200':
          description: Deleted
        '404':
          description: Not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /domains/{domain}/sensors/{sensor_id}/owner:
    put: 
      summary: insert owner 
      tags: 
      - Sensors
      consumes:
      - "text/plain"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - in: "body"
        name: "body"
        required: true
        schema:
          type: string
          description: the owner of the sensor
          example: cdupont
      responses:
        '200':
          description: Updated 
        '400':
          description: Bad request
        '404':
          description: Not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/location:
    put: 
      summary: insert location 
      tags: 
      - Sensors
      consumes:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/Location'
      responses:
        '200':
          description: Updated 
        '400':
          description: Bad request
        '404':
          description: Not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/name:
    put: 
      summary: insert name
      tags: 
      - Sensors
      consumes:
      - "text/plain"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - in: "body"
        name: "body"
        required: true
        schema:
          type: string
          description: the owner of the sensor
          example: Sensor1
      responses:
        '200':
          description: Updated 
        '400':
          description: Bad request
        '404':
          description: Not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/sensor_kind:
    put: 
      summary: insert sensor kind
      tags: 
      - Sensors
      consumes:
      - "text/plain"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - in: "body"
        name: "body"
        required: true
        schema:
          type: string
          description: the sensor kind
          example: "Soil moisture sensor"
      responses:
        '200':
          description: Updated 
        '400':
          description: Bad request
        '404':
          description: Not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/measurements:
    get: 
      summary: get measurements
      tags: 
      - Sensors
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      responses:
        '200':
          description: 
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Measurement"
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post: 
      summary: insert new measurement
      tags: 
      - Sensors
      consumes:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/Measurement'
      responses:
        '200':
          description: Measurement created/updated succesfully
        '404':
          description: Not Found
        '422':
          description: Unprocessable entity 
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/measurements/{measurement_id}:
    get: 
      summary: get measurement
      tags: 
      - Sensors
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - name: "measurement_id"
        in: "path"
        required: true 
        type: "string"
        example: "0d710b12-27e8-433d-ab3a-e05b7127eeaa"
      responses:
        '200':
          description: 
          schema:
            $ref: "#/definitions/Measurement"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Delete measurement
      description:    
      tags:
        - Sensors
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - $ref: '#/parameters/measurementId'
      responses:
        '200':
          description: deleted 
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/measurements/{measurement_id}/name:
    put: 
      summary: put measurement name
      tags: 
      - Sensors
      consumes:
      - "text/plain"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - $ref: '#/parameters/measurementId'
      - name: "body"
        in: "body"
        required: true 
        schema:
          type: string
          description: the measurement name 
          example: "TC1"
      responses:
        '200':
          description: Replaced 
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/measurements/{measurement_id}/dimension:
    put: 
      summary: put measurement dimension
      tags: 
      - Sensors
      consumes:
      - "text/plain"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - $ref: '#/parameters/measurementId'
      - name: "body"
        in: "body"
        required: true 
        schema:
          type: string
          description: the measurement dimension
          example: "temperature"
      responses:
        '200':
          description: Replaced 
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/measurements/{measurement_id}/unit:
    put: 
      summary: put measurement unit
      tags: 
      - Sensors
      consumes:
      - "text/plain"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - $ref: '#/parameters/measurementId'
      - name: "body"
        in: "body"
        required: true 
        schema:
          type: string
          description: the measurement unit
          example: "Â°C"
      responses:
        '200':
          description: Replaced 
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /domains/{domain}/sensors/{sensor_id}/measurements/{measurement_id}/values:
    get: 
      summary: get measurement values
      tags: 
      - Sensors
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - $ref: '#/parameters/measurementId'
      responses:
        '200':
          description: 
          schema:
            type: array
            items:
              $ref: "#/definitions/MeasurementValue"
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create new datapoint 
      tags:
        - Sensors
      consumes:
      - "application/json"
      parameters:
      - $ref: '#/parameters/domainParam'
      - $ref: '#/parameters/sensorId'
      - $ref: '#/parameters/measurementId'
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/MeasurementValue"
      responses:
        '201':
          description: Datapoint created succesfully
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /history:
    get:
      summary: Historical  data
      description: Query domain historical data
      tags:
        - Historical data
      responses:
        '200':
          description: Array
          schema:
            $ref: '#/definitions/HistoricalValue'
        '404':
          description: Not Found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/auth:
    post:
      tags:
        - Users
      summary: Get the access token for subsequent calls
      parameters:
        - name: credentials
          in: body
          description: auth credentials
          required: true
          schema:
            $ref: '#/definitions/AuthBody'
      responses:
        '200':
          description: Return the access token
        '404':
          description: Something wrong happened
  '/users/search/{realm}':
    get:
      tags:
        - Users
      summary: Search users with specific criteria
      security:
        - Bearer: []
      parameters:
        - name: realm
          in: path
          required: true
          description: The domain to retrieve the users from
          type: string
      responses:
        '200':
          description: return filtered users
        '404':
          description: Something wrong happened
  '/users/{realm}':
    get:
      tags:
        - Users
      summary: Get all users in a realm
      security:
        - Bearer: []
      parameters:
        - name: realm
          in: path
          required: true
          description: The domain to retrieve the users from
          type: string
      responses:
        '200':
          description: return users
        '404':
          description: Something wrong happened
  '/users/{realm}/{userid}':
    get:
      tags:
        - Users
      security:
        - Bearer: []
      parameters:
        - name: realm
          in: path
          required: true
          description: The domain to retrieve the user from
          type: string
        - name: userid
          in: path
          required: true
          description: The id of the entity to retrieve
          type: string
      responses:
        '200':
          description: Return the user with the specified id
        '404':
          description: Not found
    put:
      tags:
        - Users
      security:
        - Bearer: []
      parameters:
        - name: realm
          in: path
          required: true
          description: The domain to retrieve the user from
          type: string
        - name: userid
          in: path
          required: true
          description: The id of the entity to retrieve
          type: string
        - name: data
          in: body
          description: user data to update
          required: true
          schema:
            $ref: '#/definitions/UserUpdateBody'
      responses:
        '200':
          description: Return the user with the specified id
        '404':
          description: Not found
  /spec:
    get:
      tags:
        - Specification
      responses:
        '200':
          description: Return the API specification
